BEGIN;
CREATE TABLE LOG_DADES_METEO(ID INT AUTO_INCREMENT,DATA DATETIME, ZONA TEXT, TEMPERATURA FLOAT, PRESSIO NUMERIC,PRIMARY KEY (ID));
alter table log_dades_meteo modify PRESSIO FLOAT;
INSERT INTO LOG_DADES_METEO(DATA,ZONA,TEMPERATURA,PRESSIO) values(now(), 'S1', 21.5, 1024);

COMMIT;